# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d102568682a0ce9cfe31ad870d1fde97ffb2b90077decc6f9ba08ee49e347e02e522e49d4a54f99461571c9442ebbea488dbdadf2999779f33f0ad9363cb963

test:
  secret_key_base: 456eb28e073f5a16bc1774bb3778fbf10f4ea5b70128a89d17ba5e2a843ce0b965ad94f44bf3fec3825a7f22652ccd7d987936b0a65313d0110ca0d6167081eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
